/**
 * Canonical object key validated against the storage layout in spec section 2.6.
 */
export type ObjectKey = string & { readonly __brand: 'ObjectKey' };

/**
 * Upload session identifier generated by the Upload Function.
 */
export type UploadId = string & { readonly __brand: 'UploadId' };

/**
 * Supported image MIME type for direct uploads.
 */
export type AllowedContentType = 'image/jpeg' | 'image/png' | 'image/webp';

/**
 * Stable Upload Function error code returned in API envelopes.
 */
export type UploadErrorCode =
  | 'auction_house_mismatch'
  | 'auction_house_required'
  | 'content_type_mismatch'
  | 'file_too_large'
  | 'internal_error'
  | 'invalid_source'
  | 'invalid_request'
  | 'product_mismatch'
  | 'product_required'
  | 'r2_unavailable'
  | 'session_store_unavailable'
  | 'size_mismatch'
  | 'source_not_found'
  | 'source_unavailable'
  | 'storage_unavailable'
  | 'tombstone_write_failed'
  | 'too_many_sessions'
  | 'unsupported_content_type'
  | 'upload_not_received'
  | 'upload_session_not_found';
